---
- hosts: dbservers
  user: ubuntu
  sudo: yes
  roles:
    - db

- hosts: dbservers
  user: ubuntu
  sudo: yes
  sudo_user: postgres

  tasks:
    - name: Add postgres user
      postgresql_user: user=$database_user password=$database_password

    - name: Add postgres db
      postgresql_db: db=$database_name owner=$database_user state=present encoding='UTF-8' template='template0' lc_collate='en_US.utf8' lc_ctype='en_US.utf8'
