---
- hosts: webservers
  connection: ssh
  user: '{{ user }}'
  sudo: yes
  tasks:
    - name: Install dotfile essentials
      apt: pkg=$item state=latest install_recommends=no update_cache=yes cache_valid_time=3600
      with_items:
        - cmake
        - python-apt
        - exuberant-ctags
        - git-flow
        - htop
    - name: Set correct permisssions
      file: path=$home recurse=yes owner=$user group=$group state=directory

- hosts: webservers
  connection: ssh
  user: '{{ user }}'
  tasks:
    - name: Clone dotfiles
      git: repo=https://rob_b@bitbucket.org/rob_b/dotfiles.git dest=${home}/.dotfiles

    - name: Install dotfiles
      command: make all chdir=${home}/.dotfiles creates=${home}/.config/python/pythonrc.py
